export const FETCH_USERS_SAGA = "FETCH_USERS_SAGA";
export const FETCH_ADDITIONAL_INFO_SAGA = "FETCH_ADDITIONAL_INFO_SAGA";
export const FETCH_NEW_USERS_SAGA = "FETCH_NEW_USERS_SAGA";
export const GET_USERS = "GET_USERS";
export const GET_ADDITIONAL_INFO = "GET_ADDITIONAL_INFO";
export const CLEAR_ADDITIONAL_INFO = "CLEAR_ADDITIONAL_INFO";
export const ADD_NEW_USERS = "ADD_NEW_USERS";
